/** Major Indian cities offered in city dropdowns. "Other" lets the user type a city not listed. */
export const INDIAN_CITIES = [
  "Mumbai",
  "Delhi",
  "Bengaluru",
  "Hyderabad",
  "Ahmedabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Bhopal",
  "Patna",
  "Vadodara",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Varanasi",
  "Kota",
  "Surat",
  "Coimbatore",
  "Chandigarh",
  "Guwahati",
  "Thiruvananthapuram",
  "Dehradun",
  "Ranchi",
  "Raipur",
  "Amritsar",
] as const;

export const OTHER_CITY_OPTION = "OTHER";
