import { createFileRoute } from "@tanstack/react-router";
import { PageHero, CTAStrip } from "@/components/site/PageHero";
import { LegalCompanyCard, LegalSection, LegalTocNav } from "@/components/site/LegalLayout";

const LAST_UPDATED = "23 June 2026";

const TOC = [
  { id: "introduction", label: "Introduction" },
  { id: "information", label: "Information We Collect" },
  { id: "use", label: "How We Use Information" },
  { id: "legal-bases", label: "Legal Bases" },
  { id: "sharing", label: "Sharing & Subprocessors" },
  { id: "retention", label: "Data Retention" },
  { id: "security", label: "Security Practices" },
  { id: "your-rights", label: "Your Rights" },
  { id: "students", label: "Students & Parents" },
  { id: "cookies", label: "Cookies & Analytics" },
  { id: "transfers", label: "International Transfers" },
  { id: "changes", label: "Changes to this Policy" },
  { id: "contact", label: "Grievance Officer & Contact" },
];

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Hostylia" },
      {
        name: "description",
        content:
          "How Hostylia collects, uses and protects information. Operated by Jeevijay Technologies Private Limited.",
      },
      { property: "og:title", content: "Privacy Policy — Hostylia" },
      { property: "og:description", content: "Our commitments to data privacy and protection." },
      { property: "og:url", content: "/privacy" },
    ],
    links: [{ rel: "canonical", href: "/privacy" }],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <div className="bg-section-dark">
      <PageHero
        eyebrow="Legal"
        title="Privacy Policy"
        desc={`How Hostylia collects, uses and protects information. Last updated ${LAST_UPDATED}.`}
      />

      <section className="py-16">
        <div className="mx-auto grid max-w-7xl gap-10 px-4 md:px-6 lg:grid-cols-[260px_1fr]">
          <LegalTocNav items={TOC} />

          <article className="min-w-0">
            <div className="rounded-2xl border border-gold/30 bg-gold/5 p-5 text-sm text-soft-grey">
              This page is maintained by{" "}
              <strong className="text-white">Jeevijay Technologies Private Limited</strong> to
              describe how Hostylia is operated. It is not legal advice — please consult counsel
              before relying on it for any specific compliance purpose.
            </div>

            <div className="mt-8">
              <LegalSection id="introduction" title="1. Introduction & Scope">
                <p>
                  Jeevijay Technologies Private Limited ("Hostylia", "we", "us") operates the
                  Hostylia platform, a residential management service used by hostels, boarding
                  schools, PGs, co-living spaces and similar operators. This Privacy Policy
                  describes how we collect, use, share and protect information when you visit our
                  website, use our applications or otherwise interact with the Services.
                </p>
                <p>
                  In most cases, Hostylia acts as a{" "}
                  <strong className="text-white">data processor</strong> on behalf of the
                  residential operator (the "Customer"), who is the data controller of student,
                  parent and staff information. We act as a{" "}
                  <strong className="text-white">data controller</strong> only for information
                  collected directly from website visitors, sales prospects and the Customer's
                  authorised account administrators.
                </p>
              </LegalSection>

              <LegalSection id="information" title="2. Information We Collect">
                <p>
                  <strong className="text-white">Account information</strong> — name, email, phone,
                  organisation, role and authentication details.
                </p>
                <p>
                  <strong className="text-white">Property & operations data</strong> — buildings,
                  blocks, rooms, beds, occupancy, fee structures, complaints, attendance, gate-pass
                  events and similar records uploaded or generated by the Customer.
                </p>
                <p>
                  <strong className="text-white">Student & parent information</strong> — names,
                  contact details, photographs, room assignments, fee status, attendance and other
                  information provided by the Customer.
                </p>
                <p>
                  <strong className="text-white">Payment information</strong> — billing details
                  processed by authorised payment gateways; we do not store full card numbers on our
                  systems.
                </p>
                <p>
                  <strong className="text-white">Technical & device information</strong> — IP
                  address, browser type, device identifiers, log files and cookies, used to operate
                  and secure the Services.
                </p>
                <p>
                  <strong className="text-white">Support & communications</strong> — messages you
                  send us via email, in-app chat or other channels.
                </p>
              </LegalSection>

              <LegalSection id="use" title="3. How We Use Information">
                <p>We use information to:</p>
                <ul className="list-inside list-disc space-y-2">
                  <li>Provide, operate and improve the Services.</li>
                  <li>Authenticate users and prevent unauthorised access.</li>
                  <li>Process payments, send receipts and manage subscriptions.</li>
                  <li>
                    Power AI features such as fee reminders, complaint triage and occupancy
                    insights, on behalf of the Customer.
                  </li>
                  <li>Communicate operational notices, security alerts and product updates.</li>
                  <li>Comply with legal obligations and enforce our Terms.</li>
                </ul>
              </LegalSection>

              <LegalSection id="legal-bases" title="4. Legal Bases">
                <p>Where applicable law requires a legal basis for processing, we rely on:</p>
                <ul className="list-inside list-disc space-y-2">
                  <li>
                    <strong className="text-white">Contract</strong> — to provide the Services to
                    the Customer and authorised Users.
                  </li>
                  <li>
                    <strong className="text-white">Consent</strong> — where you have given consent,
                    such as for marketing communications, which you may withdraw at any time.
                  </li>
                  <li>
                    <strong className="text-white">Legitimate interest</strong> — for security,
                    fraud prevention and product improvement, balanced against your rights.
                  </li>
                  <li>
                    <strong className="text-white">Legal obligation</strong> — to comply with tax,
                    accounting or regulatory requirements.
                  </li>
                </ul>
              </LegalSection>

              <LegalSection id="sharing" title="5. Sharing & Subprocessors">
                <p>
                  We do not sell personal information. We share information only with the following
                  categories of recipients, under appropriate confidentiality and data protection
                  commitments:
                </p>
                <ul className="list-inside list-disc space-y-2">
                  <li>
                    <strong className="text-white">Cloud infrastructure providers</strong> for
                    hosting and storage.
                  </li>
                  <li>
                    <strong className="text-white">Payment processors</strong> to collect and
                    reconcile fees.
                  </li>
                  <li>
                    <strong className="text-white">Communication providers</strong> for SMS, email
                    and WhatsApp notifications.
                  </li>
                  <li>
                    <strong className="text-white">Analytics and error-monitoring providers</strong>{" "}
                    to operate and improve the Services.
                  </li>
                  <li>
                    <strong className="text-white">Professional advisors and authorities</strong>{" "}
                    where required by law.
                  </li>
                </ul>
                <p>
                  A current list of subprocessors is available on request from{" "}
                  <a href="mailto:hello@hostylia.com" className="text-soft-teal hover:underline">
                    hello@hostylia.com
                  </a>
                  .
                </p>
              </LegalSection>

              <LegalSection id="retention" title="6. Data Retention">
                <p>
                  We retain Customer Data for as long as the Customer's subscription is active. On
                  termination, Customer Data is made available for export for a reasonable period
                  and is then deleted or anonymised, except where retention is required by law or
                  for legitimate business purposes (such as tax records).
                </p>
              </LegalSection>

              <LegalSection id="security" title="7. Security Practices">
                <p>We protect information using safeguards including:</p>
                <ul className="list-inside list-disc space-y-2">
                  <li>Encryption of data in transit using industry-standard TLS.</li>
                  <li>
                    Role-based access controls and least-privilege principles for internal access.
                  </li>
                  <li>Regular backups and disaster-recovery routines.</li>
                  <li>Audit logs for sensitive operations.</li>
                  <li>Ongoing personnel training on privacy and security.</li>
                </ul>
                <p>
                  No method of transmission or storage is 100% secure. We continuously improve our
                  controls and will notify affected Customers of material security incidents in
                  accordance with applicable law.
                </p>
              </LegalSection>

              <LegalSection id="your-rights" title="8. Your Rights">
                <p>Depending on the laws applicable to you, you may have the right to:</p>
                <ul className="list-inside list-disc space-y-2">
                  <li>Access the personal information we hold about you.</li>
                  <li>Request correction of inaccurate information.</li>
                  <li>Request deletion of your personal information.</li>
                  <li>Object to or restrict certain processing.</li>
                  <li>Request a portable copy of your information.</li>
                  <li>Withdraw consent at any time, without affecting prior processing.</li>
                </ul>
                <p>
                  If Hostylia is acting as a processor on behalf of the Customer (for example, for
                  student or parent information), please raise your request with the Customer. We
                  will support the Customer in responding.
                </p>
              </LegalSection>

              <LegalSection id="students" title="9. Students & Parents">
                <p>
                  Hostylia is deployed by residential operators that may serve minors. Operators are
                  responsible for obtaining the consents required from students and their parents or
                  guardians before uploading information to the Services. We process such
                  information strictly on the operator's instructions and provide appropriate
                  technical and organisational measures to protect it.
                </p>
              </LegalSection>

              <LegalSection id="cookies" title="10. Cookies & Analytics">
                <p>
                  We use a small number of essential cookies to authenticate sessions and remember
                  preferences. We may use privacy-respecting analytics to understand how our website
                  and applications are used. You can control cookies through your browser settings.
                </p>
              </LegalSection>

              <LegalSection id="transfers" title="11. International Data Transfers">
                <p>
                  Hostylia primarily processes Customer Data within India. Where information is
                  transferred to other countries (for example, for support or cloud services), we
                  use appropriate safeguards, including contractual commitments with our providers.
                </p>
              </LegalSection>

              <LegalSection id="changes" title="12. Changes to this Policy">
                <p>
                  We may update this Privacy Policy from time to time. If we make material changes,
                  we will notify you through the Services or by email and update the "Last updated"
                  date above.
                </p>
              </LegalSection>

              <LegalSection id="contact" title="13. Grievance Officer & Contact">
                <p>
                  For questions, complaints or to exercise your rights, please contact our Grievance
                  Officer:
                </p>
                <LegalCompanyCard />
              </LegalSection>
            </div>
          </article>
        </div>
      </section>
      <CTAStrip />
    </div>
  );
}
